[pyprland]
plugins = ["scratchpads", "shortcuts_menu"]

[scratchpads.volume]
animation = "fromTop"
command = "pavucontrol --tab=3"
class = "pavucontrol"
position = "35% 32px"
size = "65% 90%"
hysteresis = 0
unfocus = "hide"
lazy = true
excludes = "*"

[scratchpads.control]
animation = "fromTop"
command = "missioncenter"
class = "io.missioncenter.MissionCenter"
position = "30% 32px"
size = "70% 80%"
hysteresis = 0
unfocus = "hide"
lazy = true
excludes = "*"

[scratchpads.power]
animation = "fromTop"
command = "powersupply"
class = "powersupply"
position = "70% 32px"
size = "30% 70%"
hysteresis = 0
unfocus = "hide"
lazy = true
excludes = "*"

[scratchpads.calendar]
animation = "fromTop"
command = "gnome-calendar"
class = "org.gnome.Calendar"
position = "15% 32px"
size = "85% 90%"
hysteresis = 0
lazy = false
class_match = true
process_tracking = false
excludes = "*"

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class 'terminal-float'"
class = "terminal-float"
position = "15% 32px"
size = "70% 50%"
lazy = false
excludes = "*"

[scratchpads.ncmpcpp]
animation = "fromTop"
command = "alacritty --class terminal-ncmpcpp -e ncmpcpp --screen playlist --slave-screen visualizer"
class = "terminal-ncmpcpp"
position = "0% 32px"
size = "100% 97%"
lazy = true
excludes = "*"

[scratchpads.btop]
animation = "fromTop"
command = "alacritty --class terminal-btop -e btop"
class = "terminal-btop"
position = "0% 32px"
size = "100% 97%"
lazy = true
excludes = "*"

[scratchpads.bluetuith]
animation = "fromTop"
command = "alacritty --class terminal-bluetuith -e bluetuith"
class = "terminal-bluetuith"
position = "5% 32px"
size = "90% 90%"
lazy = true
excludes = "*"

[scratchpads.logs]
animation = "fromTop"
command = "alacritty --class 'hyprland-logs' -e tail -f /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log"
class = "hyprland-logs"
position = "5% 32px"
size = "90% 90%"
lazy = false
excludes = "*"

[scratchpads.socket]
animation = "fromTop"
command = "alacritty --class 'hyprland-socket' -e socat - \"UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock\""
class = "hyprland-socket"
position = "5% 32px"
size = "90% 90%"
lazy = false
excludes = "*"

[scratchpads.password]
animation = "fromTop"
command = "keepassxc"
class = "org.keepassxc.KeePassXC"
position = "2% 32px"
size = "96% 92%"
hysteresis = 0
lazy = false
excludes = "*"
