[pyprland]
plugins = ["scratchpads", "shortcuts_menu"]

[scratchpads.volume]
animation = "fromTop"
command = "pavucontrol --tab=3"
class = "pavucontrol"
position = "35% 30px"
size = "65% 90%"
hysteresis = 0
unfocus = "hide"
lazy = true

[scratchpads.control]
animation = "fromTop"
command = "missioncenter"
class = "io.missioncenter.MissionCenter"
position = "30% 30px"
size = "70% 80%"
hysteresis = 0
unfocus = "hide"
lazy = true

[scratchpads.power]
animation = "fromTop"
command = "powersupply"
class = "powersupply"
position = "70% 30px"
size = "30% 70%"
hysteresis = 0
unfocus = "hide"
lazy = true

[scratchpads.calendar]
animation = "fromTop"
command = "gnome-calendar"
class = "org.gnome.Calendar"
position = "15% 30px"
size = "85% 90%"
hysteresis = 0
lazy = false
class_match = true
process_tracking = false

[scratchpads.logs]
animation = "fromRight"
command = "alacritty --class 'hyprland-logs' -e tail -f /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log"
class = "hyprland-logs"
position = "50% 10%"
size = "50% 40%"
hysteresis = 0
lazy = true

[scratchpads.socket]
animation = "fromRight"
command = "alacritty --class 'hyprland-socket' -e socat - \"UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock\""
class = "hyprland-socket"
position = "50% 50%"
size = "50% 40%"
hysteresis = 0
lazy = true
