[pyprland]
plugins = ["scratchpads", "toggle_dpms"]

[scratchpads.volume]
animation = "fromTop"
command = "pavucontrol --tab=3"
class = "pavucontrol"
position = "20% 32px"
size = "80% 75%"
hysteresis = 0
unfocus = "hide"
lazy = true
excludes = "*"

[scratchpads.control]
animation = "fromTop"
command = "missioncenter"
class = "io.missioncenter.MissionCenter"
position = "15% 32px"
size = "85% 75%"
hysteresis = 0
unfocus = "hide"
lazy = true
excludes = "*"

[scratchpads.power]
animation = "fromTop"
command = "powersupply"
class = "powersupply"
position = "60% 32px"
size = "40% 75%"
hysteresis = 0
unfocus = "hide"
lazy = true
excludes = "*"

[scratchpads.calendar]
animation = "fromTop"
command = "gnome-calendar"
class = "org.gnome.Calendar"
position = "15% 32px"
size = "85% 85%"
hysteresis = 0
unfocus = "hide"
lazy = false
#class_match = true
#process_tracking = false
excludes = "*"

[scratchpads.terminal-float]
animation = "fromTop"
command = "alacritty --class terminal-float"
class = "terminal-float"
position = "12% 32px"
size = "76% 40%"
lazy = true
excludes = "*"

[scratchpads.pulsemixer]
animation = "fromTop"
command = "alacritty --class pulsemixer -e pulsemixer"
class = "pulsemixer"
position = "12% 32px"
size = "76% 80%"
lazy = true
excludes = "*"

[scratchpads.ncmpcpp]
animation = "fromTop"
command = "alacritty --class ncmpcpp -e ncmpcpp --screen playlist --slave-screen visualizer"
class = "ncmpcpp"
position = "3% 32px"
size = "92% 95%"
lazy = true
excludes = "*"

[scratchpads.btop]
animation = "fromTop"
command = "alacritty --class btop -e btop"
class = "btop"
position = "0% 32px"
size = "100% 97%"
lazy = true
excludes = "*"

[scratchpads.bluetuith]
animation = "fromTop"
command = "alacritty --class bluetuith -e bluetuith"
class = "bluetuith"
position = "5% 32px"
size = "90% 90%"
lazy = true
excludes = "*"

[scratchpads.logs]
animation = "fromTop"
command = "alacritty --class 'hyprland-logs' -e tail -f /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log"
class = "hyprland-logs"
position = "5% 32px"
size = "90% 90%"
lazy = true
excludes = "*"

[scratchpads.socket]
animation = "fromTop"
command = "alacritty --class 'hyprland-socket' -e socat - \"UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock\""
class = "hyprland-socket"
position = "5% 32px"
size = "90% 90%"
lazy = true
excludes = "*"
